import Head from "next/head";
import Home from "./home/index";

export default function Index() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-center h-screen bg-primary'>Food Ordering example</h1>
      <Home />
    </div>
  )
}
